### ISSUE TITLE
Any chance for python 3.5 support?

### ISSUE THREAD

**Issue by fu2re** [sobolevn/flake8-eradicate#138]

**Comment by sobolevn** [comment]
@fu2re if you send a working PR - I don't mind.

**Comment by fu2re** [comment]
I have working code, but flake8-bugbear is still require 3.6

**Comment by sobolevn** [comment]
You can drop it, now problem.

**Comment by fu2re** [comment]
ok, done

**Comment by sobolevn** [comment]
`0.4.0` is released: https://github.com/sobolevn/flake8-eradicate/releases/tag/0.4.0
