### ISSUE TITLE
Black formatting flags as code

### ISSUE THREAD

**Issue by Dreamsorcerer** [sobolevn/flake8-eradicate#147]
If you're in the unfortunate situation of having to deal with Black formatting, then this plugin catches the on/off markers as if they were code. Maybe just needs a specific whitelist for these 2 lines:

```
# fmt: off
# fmt: on
```

**Comment by sobolevn** [comment]
Can you please open the same issue in `eradicate` repo? It is on their side.

**Comment by Dreamsorcerer** [comment]
Oh, I didn't even notice. The search engine picked your repo as the first result. :P

**Comment by Dreamsorcerer** [comment]
Ah, looks like it's already been done:
https://github.com/myint/eradicate/issues/11

Also looks like there's a PR available, but it's not been looked at yet.

**Comment by Cielquan** [comment]
I had the same issue.

I made a PR at `eradicate`, which adds a whitelisting feature, which almost resolves all issues and other PRs there, but the owner seems to be very inactive. 

So I plan to write a tool (pydusting) myself which also does what `eradicate` does but with the mentioned whitelisting feature and as a click cli app.

@sobolevn Would you be interested to switch from eradicate to my project? Else I would make a flake8 extension myself.

**Comment by sobolevn** [comment]
@Cielquan I guess it is better to ask for "maintainer" rights in the original repo then creating your own stuff. Is there anything I can help you with? I would love to see `eradicate` maintained.

**Comment by Cielquan** [comment]
Sure you are right, but the rewrite would "only" take 1 or 2 days I think.

Github wise the owner is inactive but I will try to email him and ask for maintainer rights.
But if you have a contact of any kind to the owner that may help, please feel free to ask him too.

**Comment by Cielquan** [comment]
That's great to hear. Lets improve `eradicate` and close this issue 😃
