### ISSUE TITLE
Errors occurred with encoding hints that valid with PEP 263

### ISSUE THREAD

**Issue by thombashi** [sobolevn/flake8-eradicate#3]
Just FYI:

I get the following error message from `flake8-eradicate` via `pylama`:

    sample.py:1:1: E800: Found commented out code: # encoding: utf-8 [eradicate]

I often use the following encoding hint:

    # encoding: utf-8

And this style of encoding-hints is valid according to PEP 263.
valid encoding hints regular expression:

    ^[ \t\f]*#.*?coding[:=][ \t]*([-_.a-zA-Z0-9]+)

However, the current version of `eradicate` judged ` #encoding: utf-8` as a commented out code.
I try to modify the behavior to follow PEP 263 with myint/eradicate#9 for now.

**Comment by sobolevn** [comment]
@thombashi thank you! I will update to the new version of `eradicate` after a new release.

**Comment by thombashi** [comment]
I will close the issue.
myint/eradicate#9 already merged and included at `eradicate 1.0`.
