### ISSUE TITLE
flake8-eradicate and black

### ISSUE THREAD

**Issue by tobiasraabe** [sobolevn/flake8-eradicate#8]
Hi,

Thanks for the tool. Unfortunately, flake8-eradicate recognizes `# fmt: on` and `# fmt: off` as commented out code whereas the comments identify blocks which should not be formatted with black. Is it possible to exclude these patterns?

Best

**Comment by sobolevn** [comment]
@tobiasraabe thanks for reporting the issue! 

However, this is a not an appropriate place for this.
Please, open an issue for https://github.com/myint/eradicate

You can link this issue as an origin.
